import OwlComponent from '@/webowl/OwlComponent';

export const appComponent = new OwlComponent();
export const frontPageComponent = new OwlComponent();
export const mainComponent = new OwlComponent();
export const navComponent = new OwlComponent();
export const frontPageMainComponent = new OwlComponent();
export const loginButtonComponent = new OwlComponent();
export const loginEntryPopupComponent = new OwlComponent();
export const loginEntryComponent = new OwlComponent();
export const loginPopupComponent = new OwlComponent();
export const emailLoginComponent = new OwlComponent();
export const socialLoginButtonComponent = new OwlComponent();
export const emailLoginButtonComponent = new OwlComponent();
export const avatarComponent = new OwlComponent();
export const navLeftComponent = new OwlComponent();
export const navLogoComponent = new OwlComponent();
export const navIntroComponent = new OwlComponent();
export const navGithubComponent = new OwlComponent();
export const navRightComponent = new OwlComponent();
export const backgroundComponent = new OwlComponent();
export const emailSignupComponent = new OwlComponent();
